export function createSeeds() {

    const chiliMaple = new HotSauce("The Classic - Chili Maple", "Hot Ones Hot Sauce", 1, 1600, {heat: 1, fruit: 0, garlic: 6, sweet: 6, smoke: 0, salt: 9, vinegar: 9}, "Combining the natural sweetness of real maple syrup with tangy apple cider vinegar and vibrant Fresno chilis from Smokin’ Ed, The Classic Chili Maple is the perfect balance of sweet and heat, with just-right spice and a helping of garlicky umami.", ["crispy brussels sprouts", "roast chicken", "sweet potatoes", "chicken and waffles"], "hot_sauce_images/chili-maple.png");

    const curryVerde = new HotSauce("Curry Verde", "La Pimenterie", 2, 6000, {heat: 2, fruit: 0, garlic: 6, sweet: 3, smoke: 0, salt: 3, vinegar: 3}, "This Thai-inspired hot sauce is full of delicious veggies like eggplant, zucchini, and long hot peppers, plus unique aromatics and spices like galangal, lemongrass, and kaffir lime zest. It adds zesty, veggie-packed flavor to any dish.", ["coconut shrimp", "thai salad", "curries"], "hot_sauce_images/curry-verde.png");

    const zestyLemonPepper = new HotSauce("Zesty Lemon Pepper", "The Crabby Shack", 3, 15500, {heat: 3, fruit: 0, garlic: 6, sweet: 6, smoke: 0, salt: 3, vinegar: 9}, "Introducing The Crabby Shack's Zesty Lemon Pepper Hot Sauce - a favorite from the eponymous seafood restaurant in Brooklyn! Crabby Shack owners Fifi and Gwen created this tangy tomatillo and lemon pepper blend to add a kick to their lobster and crab-centric dishes.", ["fried clams", "lobster rolls", " BLTs"], "hot_sauce_images/lemon-pepper.png");
    
    const chichoGhost = new HotSauce("Chicho-Ghost", "Chile Lengua De Fuego", 4, 36500, {heat: 4, fruit: 0, garlic: 6, sweet: 6, smoke: 6, salt: 6, vinegar: 0}, "Crafted in Honduras with the perfect blend of earthy chipotle, powerful ghost pepper and subtle notes of ginger and panela sugar, this medium-heat sauce is sure to bring the sizzle to whatever you’re cooking up.", ["breakfast tacos", "BBQ chicken", "plantains"], "hot_sauce_images/chicho-ghost.png");
    
    const losCalientesRojo = new HotSauce("Los Calientes Rojo", "Hot Ones Hot Sauce", 5, 49000, {heat: 5, fruit: 6, garlic: 3, sweet: 6, smoke: 6, salt: 9, vinegar: 6}, "In this kicked-up edition of Los Calientes, applewood smoked red jalapeños lend sweetness while added citrus and an extra handful of habanero up the heat factor. A unique mix of herbs and tart apricot give the sauce its signature flavor with increased nuance for an unforgettable condiment that’s sure to be your new go-to.", ["wings", "tacos", "pizza"], "hot_sauce_images/los-calientes-rojo.png");
    
    const makoSnake = new HotSauce("Mako Snake", "The Spicy Shark", 6, 71000, {heat: 6, fruit: 6, garlic: 3, sweet: 3, smoke: 0, salt: 3, vinegar: 3}, "Join us in welcoming The Spicy Shark to the Hot Ones family! The New England-based maker is bringing heat to the sixth wing in the Hot Ones Season 21 lineup with a daring combo of Carolina Reapers and ghost peppers for lingering spice. It's an intense blend of masala spices like cumin, cinnamon, cardamom, coriander and caraway with banana, sweet potato and pineapple.", ["burgers", "curries", "grilled veggies"], "hot_sauce_images/mako-snake.png");
    
    const jalapenoChico = new HotSauce("Jalapeño Chico", "Adoboloco", 7, 103000, {heat: 7, fruit: 0, garlic: 6, sweet: 6, smoke: 9, salt: 3, vinegar: 6}, "With a blend of smoked jalapeño and super-hot Scorpion peppers plus smoked paprika, this hot sauce’s ingredients compound into intense savory and fire-roasted notes.", ["pulled pork / carnitas", "nachos", "tacos"], "hot_sauce_images/jalapeno-chico.png");
    
    const daBombEvolution = new HotSauce("Da Bomb Evolution", "Da Bomb", 8, 135000, {heat: 8, fruit: 3, garlic: 6, sweet: 9, smoke: 6, salt: 6, vinegar: 3}, "This fresh take on the hotly hyped original packs much of the same heat but with loads of flavor. Fiery red super hot scorpion peppers are balanced with hearty spices like paprika and turmeric, as well as sugar, garlic and lemon for a sauce that stops you in your tracks as much for its savory flavor as its heat. A hint of delicate herbs like cilantro and mint finish things off and leave you wanting another bite.", ["shrimp and grits", "rotisserie chicken", "oven-roasted cauliflower"], "hot_sauce_images/da-bomb.png");
    
    const watermelonGhost = new HotSauce("Watermelon Ghost", "Alchemy Peppers", 9, 641000, {heat: 9, fruit: 9, garlic: 3, sweet: 3, smoke: 0, salt: 9, vinegar: 0}, "This unique sauce blends fiery ghost peppers with refreshing watermelon, peach, mango and El Dorado hops for a bold and balanced flavor that's bursting with intensity. The floral notes of the watermelon and hops are balanced with subtle sweetness from peach and mango purees. First its sweet, then it's super-spicy thanks to a heaping serving of ghost pepper.", ["salads", "seafood", "gazpacho"], "hot_sauce_images/watermelon-ghost.png");
    
    const theLastDabApollo = new HotSauce("The Last Dab: Apollo", "Hot Ones Hot Sauce", 10, 2000000, {heat: 10, fruit: 0, garlic: 6, sweet: 6, smoke: 0, salt: 9, vinegar: 9}, "The Apollo Pepper has been carefully bred and nurtured by Guinness World Record holding chili breeder Smokin’ Ed Currie of Puckerbutt Pepper Co from prized strains of his famed Carolina Reaper and Pepper X. The Apollo brings this heritage to new heights of capsaicin, packing a more concentrated punch than any of its forebears. The flavor of The Apollo comes from the sweetness of Carolina Reaper, tinged with the earthiness of Pepper X - it’s a culinary powerhouse. The heat profile of The Apollo Pepper is akin to having your head slowly lit aflame. You feel the fire consume your entire skull, your tongue smolders, burning tears pour from your eyes. And then, five minutes later, the ride is over, your heart rate returns to normal, the panic subsides. This pepper is like no other.", ["anything, if you dare"], "hot_sauce_images/last-dab.png");

};


